name: Test, build, deploy
on: push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Run jest unit tests
        run: npm test
      - name: Run JS linter
        run: npm run lint
      - name: Run Cypress end-to-end
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          start: npm start
  deploy:
    name: Build container and deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Build the Docker image
        run: docker build -t base --build-arg GITHUB_SHA_ARG=${{ github.sha }} .
      - name: Tag :latest
        run: docker tag base cdssnc/cra-alpha:latest
      - name: Tag :$GITHUB_SHA
        run: docker tag base cdssnc/cra-alpha:${{ github.sha }}
      - name: Login into Docker Hub
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push container to Docker Hub
        run: docker push cdssnc/cra-alpha
      - name: Login to Azure
        uses: Azure/github-actions/login@d0e5a0afc6b9d8d19c9ade8e2446ef3c20e260d4
        env:
          AZURE_SERVICE_APP_ID: ${{ secrets.AZURE_SERVICE_APP_ID }}
          AZURE_SERVICE_PASSWORD: ${{ secrets.AZURE_SERVICE_PASSWORD }}
          AZURE_SERVICE_TENANT: ${{ secrets.AZURE_SERVICE_TENANT }}
      - name: Update container image in Azure App Service for Containers
        uses: Azure/github-actions/cli@d0e5a0afc6b9d8d19c9ade8e2446ef3c20e260d4
        env:
          AZURE_SCRIPT: az webapp config container set --resource-group cdscracollab-innovation-rg
            --name cra-alpha --docker-custom-image-name cdssnc/cra-alpha:$GITHUB_SHA
